# Configuration ktools
# Copier vers ~/.config/ktools/config.yaml

# Token API Infomaniak
# Cr√©er sur https://manager.infomaniak.com/v3/ng/accounts/token/list
# Scope requis: kdrive
api_token: ""

# ID du kDrive (visible dans l'URL: https://drive.infomaniak.com/app/drive/[ID]/files)
drive_id: 0

# URL de base (optionnel)
# base_url: https://api.infomaniak.com
